### PR TITLE
Enable and start systemd services with make.

### PR DESCRIPTION
**Pull request by rdmark**

### CODE REVIEW

**Comment by rdmark** [comment]
@christopherkobayashi I don't know if it's kosher to start systemd services with make, but at the very least we should enable them I think.

**Comment by christopherkobayashi** [comment]
Hmmm.  Let me think about this a bit.  I can think of one case (building a package on a build host) where "make install" should not enable the service.

**Comment by rdmark** [comment]
Maybe it can be make a configure time option? I've made this change in my fork, and find the utility this provides very convenient. :)

**Comment by rdmark** [comment]
@christopherkobayashi Added a --enable-systemd-start configure option, which is off by default. Seems to work as expected in my testing.

**Review by christopherkobayashi — APPROVED** [review]
Looks reasonable.

**Pull request merged**
